# See https://docs.docker.com/compose/compose-file/ for information about what
# commands you can use in this file.
#
# Note that you must use the `docker stack deploy` command, with any required
# command line flags, in order to actually get any replicas started. That
# command requires that a docker swarm is already running in order to function.

version: "3"
services:
  kademliaNodes:
    image: kadlab:latest # Make sure your Docker image has this name.
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 50
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    networks:
      - kademlia_network
    ports:
      - "2337"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  kademlia_network:
    driver: bridge
